name: Clean PRs deployments

on:
  workflow_dispatch: ~
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday.

jobs:

  clear-deployed-prs:
    name: '🧹 Clear'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: 'Remove PRs folder'
        run: rm -Rf pr

      - name: 'Git status'
        run: git status

      # https://github.com/EndBug/add-and-commit
      - name: 'Commit & push changes'
        uses: EndBug/add-and-commit@v4
        with:
          author_name: GitHub Actions Bot
          author_email: actions@github.com
          message: '[AUTO] Remove previous PRs deployments'
          add: "./pr"
          ref: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
