name: Generate and publish demo

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          ref: master

      # https://github.com/actions/setup-node
      - name: Setup node
        uses: actions/setup-node@v1

      - name: Generate demo
        run: make install build@demo

      - name: Deploy demo
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo
          publish_branch: gh-pages
