name: Publish ackage to NPM

on:
  release:
    types: [created]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version: '16'

    - name: Generate dist and publish
      run: make install publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
